{% set version = "0.7.5" %}

package:
  name: sqlalchemy-redshift
  version: {{ version }}

source:
  url: https://github.com/sqlalchemy-redshift/sqlalchemy-redshift/archive/{{ version }}.tar.gz
  sha256: d9344f57814e631c7a8ff0a010b4ecdd4dc984b4882e280b1691e6280d8b09bd

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - python
    - pip
  run:
    - python
    - setuptools
    - sqlalchemy >=0.9.2
    - psycopg2 >=2.5

test:
  imports:
    - sqlalchemy_redshift

about:
  home: https://github.com/sqlalchemy-redshift/sqlalchemy-redshift
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Amazon Redshift SQLAlchemy Dialect'

  doc_url: https://sqlalchemy-redshift.readthedocs.io/en/latest/
  dev_url: https://github.com/sqlalchemy-redshift/sqlalchemy-redshift

extra:
  recipe-maintainers:
    - mcg1969
